### ISSUE TITLE
Lints for D203 and D212 by default (conflicting checks!)

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter-pydocstyle#11]
While creating a new linter plugin and the default configuration of

```js
{
    "@python": 3,
    "linters": {
        "flake8": {
            "max-line-length": 120
        },
        "pep257": {
            "add-ignore": ["D202"]
        },
        "pep8": {
            "max-line-length": 120
        }
    }
}
```
in the project's `.sublimelinterrc` (and nothing in my user preferences besides default settings), I seem to get different from when I run the tool from the console. According to [the docs](http://pydocstyle.readthedocs.org/en/latest/error_codes.html#default-checks), D203, D211 (it reads "D212" but contextually I believe this should be 211) and D213 are turned off by default, but SublimeLinter detects them nonetheless.

---

Initial results:
```
SublimeLinter: pep257: linter.py <builtin> 
SublimeLinter: pep257 options: {'add-ignore': ['D202'], 'ignore': []} 
SublimeLinter: pep257 output:
linter.py:23 in public class `SublimeSyntax`:
        D203: 1 blank line required before class docstring (found 0) 
```
After attempting to satisfy pep257 by inserting a newline as requested:
```
SublimeLinter: pep257: linter.py <builtin> 
SublimeLinter: pep257 options: {'add-ignore': ['D202'], 'ignore': []} 
SublimeLinter: pep257 output:
linter.py:23 in public class `SublimeSyntax`:
        D211: No blank lines allowed before class docstring (found 1) 
```
Command Prompt:
```
c:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-sublime-syntax>pep257.exe --add-ignore D202 .

```
(yes, that's no output, as expected)

**Comment by FichteFoll** [comment]
I assume this happens because `ignore` is specifically specified as `[]` and would override the default ignored warnings when passed via cmdline (or in-module, idk).

**Comment by groteworld** [comment]
Thanks for pointing this out. `ignore` sublimelinter config has been removed for now, `ignore` can still be added with `args` config setting.
