### ISSUE TITLE
Error codes are not channeled into warning and error...

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter-pydocstyle#17]
... but are attached to lint message string.

This will prevent custom highlights with the upcoming release of SublimeLinter.
https://github.com/SublimeLinter/SublimeLinter3/pull/665

**Comment by braver** [comment]
@pykong if you can fix it I can merge it?

**Comment by maks500** [comment]
@pykong I cant test it right now but my changes should fix this.
