### ISSUE TITLE
Cannot parse file

### ISSUE THREAD

**Issue by revotus** [SublimeLinter/SublimeLinter-pydocstyle#22]
I have lately been getting this strange error in the console:

WARNING:SublimeLinter.lint.linter:pydocstyle output:
WARNING: Error in file /var/folders/8z/6b320qcs29l_9162n11cwcvs3wscc8/T/tmp5d2xz7.py: Cannot parse file.

I have tried reinstalling the package as well as the main sublimelinter package, but to no avail. The flake8 plugin for sublimelinter is working fine.

**Comment by kaste** [comment]
:+1: That's probably a good first issue.

To get better error reporting in general, SublimeLinter changed here and escalates some stderr output.

The way to go here is probably just like in https://github.com/SublimeLinter/SublimeLinter-pylint/blob/master/linter.py to implement on_stderr and filter some expected, transient errors.

**Comment by braver** [comment]
Not being able to parse a file isn’t a transient warning though right? Seems to me like there’s really something wrong?

**Comment by revotus** [comment]
FTR, the errors were gone by the end of the day. Not sure what it was about. Didn't do anything myself.
